FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update && apt-get install -y postgresql-client

COPY requirements-web.txt .
RUN pip install --no-cache-dir -r requirements-web.txt

COPY . .