version: '3.8'

services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  web:
    build:
      context: .
      dockerfile: Dockerfile-django
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env
    networks:
      - my_network

  websocket:
    build:
      context: .
      dockerfile: Dockerfile-websocket
    command: python -m websocket.websocket_server
    volumes:
      - .:/app
    ports:
      - "8765:8765"
    environment:
      - HOST=0.0.0.0
      - PORT=8765
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
