# Generated by Django 3.2.25 on 2025-02-25 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dementia_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utterance',
            options={},
        ),
    ]
